version: '2'
services:
    mpm_ng-app:
        image: mpm_ng
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mpm_ng-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=MPM_NG
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mpm_ng-mongodb:
        extends:
            file: mongodb.yml
            service: mpm_ng-mongodb
